import { Product } from "@/types/product";

export const MOCK_PRODUCTS: Product[] = [
    {
        _id: "1",
        id: "1",
        name: "Friendship Day Pink Hamper",
        price: 2499,
        salePrice: 1999,
        image: "/images/hampers/hamper-1.jpg",
        images: ["/images/hampers/hamper-1.jpg"],
        category: "Gift Hampers",
        rating: 4.8,
        stock: 10,
        description: "A lovely pink themed hamper with chocolates, artificial flowers, and a personalized card.",
        discountPercentage: 20,
        type: "Premium"
    },
    {
        _id: "7",
        id: "7",
        name: "Raksha Bandhan Chocolate Tray",
        price: 1599,
        salePrice: 1299,
        image: "/images/hampers/hamper-2.jpg",
        images: ["/images/hampers/hamper-2.jpg"],
        category: "Gift Hampers",
        rating: 4.9,
        stock: 15,
        description: "Festive wooden tray arrangement with Hershey's chocolates, dry fruits, and Rakhi decor.",
        discountPercentage: 18,
        type: "Standard"
    },
    {
        _id: "8",
        id: "8",
        name: "Elegant Floral Ring Basket",
        price: 3200,
        salePrice: 2899,
        image: "/images/hampers/hamper-3.jpg",
        images: ["/images/hampers/hamper-3.jpg"],
        category: "Gift Hampers",
        rating: 5.0,
        stock: 5,
        description: "Exquisite golden flowing basket with cascading artificial roses and tulle packaging.",
        discountPercentage: 10,
        type: "Premium"
    },
    {
        _id: "9",
        id: "9",
        name: "Golden Cage Hamper Set",
        price: 1899,
        salePrice: 1499,
        image: "/images/hampers/hamper-4.jpg",
        images: ["/images/hampers/hamper-4.jpg"],
        category: "Gift Hampers",
        rating: 4.7,
        stock: 20,
        description: "Stylish golden cage hampers with floral accents, perfect for gifting chocolates or dry fruits.",
        discountPercentage: 21,
        type: "Standard"
    },
    {
        _id: "10",
        id: "10",
        name: "Blue Trousseau Platter",
        price: 2100,
        salePrice: 1899,
        image: "/images/hampers/hamper-5.jpg",
        images: ["/images/hampers/hamper-5.jpg"],
        category: "Gift Hampers",
        rating: 4.8,
        stock: 8,
        description: "Beautifully wrapped blue themed trousseau packing with net and flower decorations.",
        discountPercentage: 10,
        type: "Custom"
    },
    {
        _id: "11",
        id: "11",
        name: "Dairy Milk Rose Bouquet",
        price: 999,
        salePrice: 849,
        image: "/images/hampers/dairy-milk-bouquet.png",
        images: ["/images/hampers/dairy-milk-bouquet.png"],
        category: "Chocolate Hampers",
        rating: 4.9,
        stock: 30,
        description: "A stunning bouquet arrangement of Dairy Milk Silk chocolates and artificial red roses.",
        discountPercentage: 15,
        type: "Standard"
    },
    {
        _id: "12",
        id: "12",
        name: "Bournville Dark Delight",
        price: 1199,
        salePrice: 999,
        image: "/images/hampers/bournville-delight.jpg",
        images: ["/images/hampers/bournville-delight.jpg"],
        category: "Chocolate Hampers",
        rating: 4.9,
        stock: 20,
        description: "Premium dark chocolate selection featuring Bourville in an elegant vase arrangement.",
        discountPercentage: 17,
        type: "Premium"
    },
    {
        _id: "13",
        id: "13",
        name: "Floral Beige Ring Platter",
        price: 2499,
        salePrice: 1999,
        image: "/images/ring-platters/floral-beige-platter-v2.jpg",
        images: ["/images/ring-platters/floral-beige-platter-v2.jpg"],
        category: "Engagement Ring Plate Deco",
        rating: 4.9,
        stock: 5,
        description: "Rustic wooden ring platter featuring large beige handcrafted flowers and golden accents.",
        discountPercentage: 20,
        type: "Custom"
    },
    {
        _id: "14",
        id: "14",
        name: "Personalized Name Ring Holder",
        price: 1899,
        salePrice: 1599,
        image: "/images/ring-platters/couple-name-platter.jpg",
        images: ["/images/ring-platters/couple-name-platter.jpg"],
        category: "Engagement Ring Plate Deco",
        rating: 4.8,
        stock: 8,
        description: "Elegant floral ring holder with custom acrylic names (e.g., Deepesh & Suhani) in a gold ring frame.",
        discountPercentage: 15,
        type: "Standard"
    },
    {
        _id: "15",
        id: "15",
        name: "Pink Velvet Hexagon Box Pair",
        price: 1299,
        salePrice: 999,
        image: "/images/ring-platters/pink-velvet-box.png",
        images: ["/images/ring-platters/pink-velvet-box.png"],
        category: "Engagement Ring Plate Deco",
        rating: 4.7,
        stock: 12,
        description: "A pair of premium pink velvet hexagon ring boxes, perfect for his and hers rings.",
        discountPercentage: 23,
        type: "Premium"
    },
    {
        _id: "2",
        id: "2",
        name: "Ferrero Rocher & Roses Bouquet",
        price: 1299,
        salePrice: 999,
        image: "/images/hampers/ferrero-bouquet.png",
        images: ["/images/hampers/ferrero-bouquet.png"],
        category: "Chocolate Hampers",
        rating: 4.9,
        stock: 25,
        description: "A beautiful arrangement of premium chocolates and artificial roses.",
        discountPercentage: 23,
        type: "Standard"
    },
    {
        _id: "3",
        id: "3",
        name: "Engagement Ring Platter - Floral",
        price: 3500,
        salePrice: 2999,
        image: "/images/ring-platters/floral-ring-platter-updated.jpg",
        images: ["/images/ring-platters/floral-ring-platter-updated.jpg"],
        category: "Engagement Ring Plate Deco",
        rating: 4.7,
        stock: 5,
        description: "Handcrafted engagement ring platter with floral decorations and personalized names.",
        discountPercentage: 14,
        type: "Custom"
    },
    {
        _id: "4",
        id: "4",
        name: "Customized Photo Lamp",
        price: 1599,
        salePrice: 1299,
        image: "/images/Category/accessories.png", // Placeholder
        images: ["/images/Category/accessories.png"],
        category: "Customized Gifts",
        rating: 4.6,
        stock: 50,
        description: "Personalized 3D moon lamp with your photo and text.",
        discountPercentage: 18,
        type: "Custom"
    },
    {
        _id: "5",
        id: "5",
        name: "Satin Ribbon Set - Pastel Pink",
        price: 299,
        salePrice: 249,
        image: "/images/Category/dog.png", // Placeholder
        images: ["/images/Category/dog.png"],
        category: "Others",
        rating: 4.9,
        stock: 100,
        description: "Luxurious satin ribbons in a set of 3 pastel shades.",
        discountPercentage: 17,
        type: "Standard"
    },
    {
        _id: "6",
        id: "6",
        name: "Metallic Gift Bag - Medium",
        price: 129,
        salePrice: 129,
        image: "/images/Category/cat.png", // Placeholder
        images: ["/images/Category/cat.png"],
        category: "Others",
        rating: 4.4,
        stock: 80,
        description: "Shiny metallic gift bag with sturdy handles.",
        discountPercentage: 0,
        type: "Standard"
    }
];
